#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  3 14:09:01 2018

@author: tianqiu
"""
# import the necessary packages
import numpy as np
import cv2
from cv2 import aruco, imshow, waitKey, imwrite
import imutils
from imutils import resize
import sys

aruco_dict = aruco.Dictionary_get(aruco.DICT_6X6_250)
parameters = aruco.DetectorParameters_create()

image = cv2.imread("image.png")
corners, ids, rejected = aruco.detectMarkers(image, aruco_dict, 
                                             parameters=parameters)
w1 = corners[0][0][0][0]
w2 = corners[0][0][1][0]
l1 = corners[0][0][0][1]
l2 = corners[0][0][1][1]

PIXEL_WIDTH = (((w2 - w1)**2) + (l2 - l1)**2)**(1/2)

# initialize the known distance from the camera to the object
KNOWN_DISTANCE = 43.18

# initialize the known width of the marker
KNOWN_WIDTH = 4.445

FOCAL_LENGTH = (PIXEL_WIDTH * KNOWN_DISTANCE) / KNOWN_WIDTH

